import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
const read=(path)=>readFile(new URL(`../${path}`,import.meta.url),"utf8");
test("Module 1 uses the app database",async()=>{const runtime=await read("db/runtime.ts");const schema=await read("db/schema.ts");assert.match(runtime,/node:sqlite/);assert.match(runtime,/DATABASE_PATH/);for(const table of ["provinces","destinations","categories","providers","listings"])assert.match(schema,new RegExp(`sqliteTable\\(\\"${table}\\"`))});
test("catalogue API is database-backed and filterable",async()=>{const api=await read("app/api/catalogue/route.ts");const service=await read("db/catalogue.ts");assert.match(api,/getCatalogue/);assert.match(service,/SELECT l\.id/);assert.match(service,/c\.slug=\?/);assert.match(service,/is_test_data/);assert.doesNotMatch(await read("app/page.tsx"),/const places\s*=/)});
test("seed records are traceable and clearly non-production",async()=>{const service=await read("db/catalogue.ts");assert.match(service,/Official provider website/);assert.match(service,/seededTestData:true/);assert.match(service,/source_url/);assert.match(service,/last_reviewed_at/)});
test("migration creates the full catalogue graph",async()=>{const sql=await read("drizzle/0000_serious_cardiac.sql");for(const table of ["categories","destinations","listings","providers","provinces"])assert.ok(sql.includes("CREATE TABLE `"+table+"`"));assert.match(sql,/FOREIGN KEY/)});

test("Module 2 uses Visit PNG accounts and server-side authorization",async()=>{const page=await read("app/page.tsx");const auth=await read("app/auth.ts");const route=await read("app/api/profile/route.ts");assert.match(page,/getVisitPngUser/);assert.match(auth,/auth_sessions/);assert.match(auth,/scryptSync/);assert.match(route,/if\(!identity\).*401/)});
test("accounts persist profiles, roles, and audit history",async()=>{const schema=await read("db/schema.ts");const service=await read("db/accounts.ts");const migration=await read("drizzle/0001_military_captain_marvel.sql");assert.match(schema,/sqliteTable\(\"users\"/);assert.match(schema,/sqliteTable\(\"audit_logs\"/);assert.match(service,/profile_updated/);assert.match(service,/role TEXT NOT NULL DEFAULT 'traveller'/);assert.match(migration,/CREATE TABLE `users`/);assert.match(migration,/CREATE TABLE `audit_logs`/)});
test("profile writes are allowlisted and cannot change roles",async()=>{const route=await read("app/api/profile/route.ts");assert.match(route,/preferredName/);assert.match(route,/preferredLanguage/);assert.doesNotMatch(route,/body\.role/)});
test("Visit PNG palette is centralized",async()=>{const theme=await read("app/theme.css");for(const colour of ["#1B6960","#E77522","#DE7739","#418F8A","#A2CECA","#EFB00D","#FAF7F2","#FFFFFF","#232231","#85848A"])assert.ok(theme.includes(colour));const css=await read("app/globals.css");assert.doesNotMatch(css,/#[0-9a-f]{3,8}/i);assert.match(css,/var\(--action-primary\)/);assert.match(css,/:focus-visible/)});
test("legacy colours are retired",async()=>{const files=[await read("app/globals.css"),await read("app/theme.css"),await read("public/favicon.svg")].join("\n");for(const legacy of ["#12221d","#124a36","#d8ef62","#f6f4ec","#68C4FF","#0C79D8","#2E9EFF"])assert.ok(!files.toLowerCase().includes(legacy.toLowerCase()))});
test("future module colour contracts are documented",async()=>{const guide=await read("docs/design-system.md");for(const area of ["Maps","Charts","Email","Print","dark mode","danger","focus"])assert.match(guide,new RegExp(area,"i"))});

test("Ubuntu is the sole product typeface",async()=>{const css=await read("app/globals.css");assert.match(css,/fonts\.googleapis\.com.*Ubuntu/);assert.match(css,/font-family:"Ubuntu"/);assert.doesNotMatch(css,/Georgia|Times New Roman/)});
test("Module 3 persists authenticated multi-list wishlists",async()=>{const schema=await read("db/schema.ts");const service=await read("db/wishlists.ts");const route=await read("app/api/wishlists/route.ts");const migration=await read("drizzle/0002_wishlist_module.sql");for(const table of ["wishlists","wishlist_items"])assert.match(schema,new RegExp(`sqliteTable\\(\"${table}\"`));assert.match(service,/user_id=\?/);assert.match(service,/wishlist_item_added/);assert.match(service,/share_code/);assert.match(route,/Please sign in/);assert.match(migration,/UNIQUE INDEX `wishlist_items_unique`/)});
test("Module 3 UI supports save, organise, notes, moves and offline cache",async()=>{const ui=await read("app/VisitPngApp.tsx");for(const feature of ["SaveSheet","SavedScreen","New wishlist name","Add a note","Move","visitpng-wishlists","Copy share link"])assert.match(ui,new RegExp(feature,"i"));assert.match(ui,/setTab\(\"Saved\"\)/)});
test("Module 4 persists owned trips, collaborators and itinerary days",async()=>{const schema=await read("db/schema.ts");const service=await read("db/trips.ts");const route=await read("app/api/trips/route.ts");const migration=await read("drizzle/0003_trip_planner.sql");for(const table of ["trips","trip_collaborators","itinerary_items"])assert.match(schema,new RegExp(`sqliteTable\\(\"${table}\"`));assert.match(service,/WHERE id=\? AND user_id=\?/);assert.match(service,/trip_collaborator_invited/);assert.match(route,/Please sign in/);assert.match(migration,/itinerary_trip_date_idx/)});
test("Module 4 UI covers planning, budgets, conflicts and offline packs",async()=>{const ui=await read("app/VisitPngApp.tsx");for(const feature of ["TripsScreen","Create trip","Add to the itinerary","Schedule conflict","Save trip copy","Add to trip","Booking reference","Travel companion email"])assert.match(ui,new RegExp(feature,"i"));assert.match(ui,/setTab\(\"Trips\"\)/)});
test("Module 5 stores configurable memberships, benefits and loyalty",async()=>{const schema=await read("db/schema.ts");const service=await read("db/membership.ts");const route=await read("app/api/membership/route.ts");const migration=await read("drizzle/0004_membership_loyalty.sql");for(const table of ["membership_plans","membership_benefits","membership_subscriptions","benefit_redemptions","loyalty_ledger"])assert.match(schema,new RegExp(`sqliteTable\\(\"${table}\"`));assert.match(service,/is_test_data/);assert.match(service,/payment_due/);assert.match(service,/usage limit/i);assert.match(route,/Please sign in/);assert.match(migration,/membership_user_current_idx/)});
test("Module 5 UI is readable and never presents false payment activation",async()=>{const ui=await read("app/VisitPngApp.tsx");const css=await read("app/globals.css");for(const feature of ["MembershipScreen","membership card","Reward balance","Use this benefit","no real money","Practice payment needed"])assert.match(ui,new RegExp(feature,"i"));assert.equal((css.match(/background:var\(--brand-white\)/g)||[]).length,1);assert.match(css,/\.memberCode\{[^}]*background:var\(--brand-white\)/);assert.match(css,/\.planCard\{[^}]*background:var\(--surface-card\);color:var\(--text-primary\)/);assert.match(css,/\.memberCard\{[^}]*background:var\(--surface-premium\);color:var\(--text-on-dark\)/)});

test("Module 6 persists owned bookings, dated inventory and payment records",async()=>{const schema=await read("db/schema.ts");const service=await read("db/bookings.ts");const route=await read("app/api/bookings/route.ts");const migration=await read("drizzle/0005_booking_payments.sql");for(const table of ["listing_inventory","bookings","booking_items","payments"])assert.match(schema,new RegExp(`sqliteTable\\(\\"${table}\\"`));assert.match(service,/hold_expires_at/);assert.match(service,/WHERE id=\? AND user_id=\?/);assert.match(route,/Please sign in/);assert.match(migration,/inventory_listing_date_idx/)});
test("Module 6 uses an unmistakable test gateway without card collection",async()=>{const ui=await read("app/VisitPngApp.tsx");const service=await read("db/bookings.ts");for(const feature of ["BookingsScreen","Check availability & hold","Confirm practice payment","card details","no real money","15 minutes"])assert.match(ui,new RegExp(feature,"i"));assert.match(service,/test_gateway/);assert.match(service,/isTestData/);assert.doesNotMatch(ui,/card number|cvv|security code/i)});
test("Module 6 booking surfaces preserve semantic text contrast",async()=>{const css=await read("app/globals.css");assert.match(css,/\.bookingSheet\{[^}]*background:var\(--surface-card\)/);assert.match(css,/\.testGateway\{[^}]*background:var\(--derived-teal-soft\);color:var\(--text-primary\)/);assert.match(css,/\.bookingCard\{[^}]*background:var\(--surface-card\);color:var\(--text-primary\)/)});

test("Module 7 persists reviews, moderation history and disputes",async()=>{const schema=await read("db/schema.ts");const service=await read("db/reviews.ts");const route=await read("app/api/reviews/route.ts");const migration=await read("drizzle/0006_reviews_reputation.sql");for(const table of ["reviews","review_moderation_events","review_disputes"])assert.match(schema,new RegExp(`sqliteTable\\(\\"${table}\\"`));assert.match(service,/verified_booking/);assert.match(service,/moderation_status='published'/);assert.match(service,/WHERE id=\? AND user_id=\?/);assert.match(route,/Please sign in/);assert.match(migration,/reviews_listing_status_idx/)});
test("Module 7 UI distinguishes verified and unverified reviews",async()=>{const ui=await read("app/VisitPngApp.tsx");for(const feature of ["ReviewsScreen","ReviewSummary","Write a review","Verified booking","Unverified visit","Fair review checks","Business reply","personal information","Honest negative feedback"])assert.match(ui,new RegExp(feature,"i"))});
test("Module 7 review surfaces use readable semantic colours",async()=>{const css=await read("app/globals.css");assert.match(css,/\.reviewSheet\{[^}]*background:var\(--surface-card\)/);assert.match(css,/\.reviewPolicy\{[^}]*background:var\(--derived-teal-soft\);color:var\(--text-primary\)/);assert.match(css,/\.myReviews>article\{[^}]*background:var\(--surface-card\);color:var\(--text-primary\)/)});

test("Customer text stays clear and readable",async()=>{const ui=await read("app/VisitPngApp.tsx");const css=await read("app/globals.css");for(const word of [/LIVE CATALOGUE API/i,/simulated gateway/i,/seeded test price/i,/identity-aware/i,/fair moderation/i])assert.doesNotMatch(ui,word);assert.match(css,/small\{font-size:11px!important/);assert.match(await read("app/theme.css"),/--text-secondary:#5F5E65/)});





test("Header brand name stays visible",async()=>{const css=await read("app/globals.css");assert.match(css,/\.app>header \.brand\{color:var\(--text-on-dark\)\}/);assert.match(css,/\.app>header \.brand span\{[^}]*display:block;[^}]*color:var\(--text-on-dark\)/)});