import {env} from "cloudflare:workers";
import type {ChatGPTUser} from "../app/chatgpt-auth";
const accountSchema=[`CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT,email TEXT NOT NULL UNIQUE,full_name TEXT,preferred_name TEXT,mobile TEXT,country TEXT NOT NULL DEFAULT 'Papua New Guinea',preferred_language TEXT NOT NULL DEFAULT 'English',role TEXT NOT NULL DEFAULT 'traveller',status TEXT NOT NULL DEFAULT 'active',created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`,`CREATE UNIQUE INDEX IF NOT EXISTS users_email_unique ON users(email)`,`CREATE TABLE IF NOT EXISTS audit_logs (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER REFERENCES users(id),actor_email TEXT NOT NULL,action TEXT NOT NULL,entity_type TEXT NOT NULL,entity_id TEXT,details TEXT,created_at TEXT NOT NULL)`,`CREATE INDEX IF NOT EXISTS audit_logs_user_idx ON audit_logs(user_id)`,`CREATE INDEX IF NOT EXISTS audit_logs_created_idx ON audit_logs(created_at)`];
export type AccountProfile={id:number;email:string;fullName:string|null;preferredName:string|null;mobile:string|null;country:string;preferredLanguage:string;role:"traveller"|"provider"|"administrator";status:string;createdAt:string;updatedAt:string};
export async function ensureAccounts(){await env.DB.batch(accountSchema.map(sql=>env.DB.prepare(sql)))}
export async function getOrCreateAccount(identity:ChatGPTUser):Promise<AccountProfile>{await ensureAccounts();const now=new Date().toISOString();await env.DB.prepare(`INSERT INTO users (email,full_name,preferred_name,country,preferred_language,role,status,created_at,updated_at) VALUES (?,?,?,?,?,'traveller','active',?,?) ON CONFLICT(email) DO UPDATE SET full_name=COALESCE(excluded.full_name,users.full_name)`).bind(identity.email,identity.fullName,identity.fullName,"Papua New Guinea","English",now,now).run();const user=await env.DB.prepare(`SELECT id,email,full_name AS fullName,preferred_name AS preferredName,mobile,country,preferred_language AS preferredLanguage,role,status,created_at AS createdAt,updated_at AS updatedAt FROM users WHERE email=?`).bind(identity.email).first<AccountProfile>();if(!user)throw new Error("Account could not be created");const existing=await env.DB.prepare("SELECT id FROM audit_logs WHERE user_id=? AND action='account_created' LIMIT 1").bind(user.id).first();if(!existing)await audit(user.id,identity.email,"account_created","user",String(user.id),{source:"siwc"});return user}
export async function updateAccount(identity:ChatGPTUser,input:{preferredName:string;mobile:string;country:string;preferredLanguage:string}){const user=await getOrCreateAccount(identity);const now=new Date().toISOString();await env.DB.prepare(`UPDATE users SET preferred_name=?,mobile=?,country=?,preferred_language=?,updated_at=? WHERE id=?`).bind(input.preferredName||null,input.mobile||null,input.country,input.preferredLanguage,now,user.id).run();await audit(user.id,identity.email,"profile_updated","user",String(user.id),{fields:["preferredName","mobile","country","preferredLanguage"]});return getOrCreateAccount(identity)}
export async function getAccountAudit(identity:ChatGPTUser){const user=await getOrCreateAccount(identity);const rows=await env.DB.prepare(`SELECT action,entity_type AS entityType,details,created_at AS createdAt FROM audit_logs WHERE user_id=? ORDER BY created_at DESC LIMIT 10`).bind(user.id).all();return rows.results}
async function audit(userId:number,email:string,action:string,entityType:string,entityId:string,details:unknown){await env.DB.prepare(`INSERT INTO audit_logs (user_id,actor_email,action,entity_type,entity_id,details,created_at) VALUES (?,?,?,?,?,?,?)`).bind(userId,email,action,entityType,entityId,JSON.stringify(details),new Date().toISOString()).run()}
