import {env} from "./runtime";import type {VisitPngUser} from "../app/auth";import {getOrCreateAccount} from "./accounts";import {ensureBookings} from "./bookings";
const schema=[`CREATE TABLE IF NOT EXISTS reviews (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL REFERENCES users(id),listing_id INTEGER NOT NULL REFERENCES listings(id),booking_id INTEGER REFERENCES bookings(id),verification_type TEXT NOT NULL DEFAULT 'unverified',overall_rating INTEGER NOT NULL,value_rating INTEGER,service_rating INTEGER,safety_rating INTEGER,accessibility_rating INTEGER,title TEXT NOT NULL,body TEXT NOT NULL,travel_type TEXT,date_of_experience TEXT,moderation_status TEXT NOT NULL DEFAULT 'published',moderation_reason TEXT,provider_response TEXT,provider_responded_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`,`CREATE INDEX IF NOT EXISTS reviews_listing_status_idx ON reviews(listing_id,moderation_status,created_at)`,`CREATE TABLE IF NOT EXISTS review_moderation_events (id INTEGER PRIMARY KEY AUTOINCREMENT,review_id INTEGER NOT NULL REFERENCES reviews(id) ON DELETE CASCADE,actor_user_id INTEGER REFERENCES users(id),action TEXT NOT NULL,reason TEXT,created_at TEXT NOT NULL)`,`CREATE TABLE IF NOT EXISTS review_disputes (id INTEGER PRIMARY KEY AUTOINCREMENT,review_id INTEGER NOT NULL REFERENCES reviews(id),raised_by_user_id INTEGER NOT NULL REFERENCES users(id),reason TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'open',resolution TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`];
let reviewsInitPromise: Promise<void> | null = null;
export async function ensureReviews(){
  if(reviewsInitPromise)return reviewsInitPromise;
  reviewsInitPromise=(async()=>{
    await ensureBookings();
    await env.DB.batch(schema.map(x=>env.DB.prepare(x)));
  })();
  return reviewsInitPromise;
}
function moderation(title:string,body:string){const text=`${title} ${body}`;if(/\b(kill|rape|nigger|terrorist threat)\b/i.test(text))return{status:"rejected",reason:"Potential abusive or threatening content"};if(/(?:\+?\d[\d\s-]{7,}|[\w.+-]+@[\w.-]+\.[a-z]{2,})/i.test(text))return{status:"pending",reason:"Potential personal information requires review"};if(/https?:\/\/|www\./i.test(text))return{status:"pending",reason:"Links require spam review"};return{status:"published",reason:null}}
async function owner(identity:VisitPngUser){await ensureReviews();return getOrCreateAccount(identity)}
export async function getListingReviews(listingId:number){await ensureReviews();const rows=await env.DB.prepare(`SELECT r.id,r.overall_rating AS overallRating,r.value_rating AS valueRating,r.service_rating AS serviceRating,r.safety_rating AS safetyRating,r.accessibility_rating AS accessibilityRating,r.title,r.body,r.travel_type AS travelType,r.date_of_experience AS dateOfExperience,r.verification_type AS verificationType,r.provider_response AS providerResponse,r.provider_responded_at AS providerRespondedAt,r.created_at AS createdAt,COALESCE(u.preferred_name,u.full_name,'ZamRoam traveller') AS author FROM reviews r JOIN users u ON u.id=r.user_id WHERE r.listing_id=? AND r.moderation_status='published' ORDER BY r.created_at DESC`).bind(listingId).all();const summary=await env.DB.prepare("SELECT COUNT(*) AS count,ROUND(AVG(overall_rating),1) AS average FROM reviews WHERE listing_id=? AND moderation_status='published'").bind(listingId).first<{count:number;average:number|null}>();const reviews=rows.results||[];const count=Number(summary?.count||reviews.length||0);const averageRating=Number(summary?.average||5.0);const verifiedCount=reviews.filter((r:Record<string,unknown>)=>r.verificationType==="verified_booking").length;return{count,averageRating,verifiedCount,aspects:{safety:null,service:null,value:null,accessibility:null},reviews,summary:{count,average:averageRating}}}
export async function getMyReviews(identity:VisitPngUser){const user=await owner(identity);const rows=await env.DB.prepare(`SELECT r.id,r.listing_id AS listingId,l.name AS listingName,l.image_url AS imageUrl,r.overall_rating AS overallRating,r.title,r.body,r.verification_type AS verificationType,r.moderation_status AS moderationStatus,r.moderation_reason AS moderationReason,r.created_at AS createdAt FROM reviews r JOIN listings l ON l.id=r.listing_id WHERE r.user_id=? ORDER BY r.created_at DESC`).bind(user.id).all();return rows.results}
export async function createReview(identity:VisitPngUser,input:Record<string,unknown>){const user=await owner(identity);const listingId=Number(input.listingId),rating=Number(input.overallRating);const title=String(input.title||"").trim().slice(0,100),body=String(input.body||"").trim().slice(0,1500);if(!listingId||rating<1||rating>5||title.length<3||body.length<10)throw new Error("Add a rating, title and review of at least 10 characters");const listing=await env.DB.prepare("SELECT id FROM listings WHERE id=? AND publication_status='published'").bind(listingId).first();if(!listing)throw new Error("Listing unavailable");const booking=await env.DB.prepare("SELECT id FROM bookings WHERE user_id=? AND status='confirmed' AND end_date<=date('now') AND id IN (SELECT booking_id FROM booking_items WHERE listing_id=?) ORDER BY end_date DESC LIMIT 1").bind(user.id,listingId).first<{id:number}>();const mod=moderation(title,body),now=new Date().toISOString();await env.DB.prepare(`INSERT INTO reviews (user_id,listing_id,booking_id,verification_type,overall_rating,value_rating,service_rating,safety_rating,accessibility_rating,title,body,travel_type,date_of_experience,moderation_status,moderation_reason,created_at,updated_at) VALUES (?,?,?, ?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(user.id,listingId,booking?.id||null,booking?"verified_booking":"unverified",rating,Number(input.valueRating)||null,Number(input.serviceRating)||null,Number(input.safetyRating)||null,Number(input.accessibilityRating)||null,title,body,String(input.travelType||"solo").slice(0,30),String(input.dateOfExperience||"").slice(0,10)||null,mod.status,mod.reason,now,now).run();const id=await env.DB.prepare("SELECT id FROM reviews WHERE user_id=? ORDER BY id DESC LIMIT 1").bind(user.id).first<{id:number}>();if(id)await env.DB.batch([env.DB.prepare("INSERT INTO review_moderation_events (review_id,actor_user_id,action,reason,created_at) VALUES (?,?,?,?,?)").bind(id.id,user.id,mod.status==="published"?"automated_publish":"automated_hold",mod.reason,now),env.DB.prepare("INSERT INTO audit_logs (user_id,actor_email,action,entity_type,entity_id,details,created_at) VALUES (?,?,?,?,?,?,?)").bind(user.id,identity.email,"review_submitted","review",String(id.id),JSON.stringify({listingId,verificationType:booking?"verified_booking":"unverified",moderationStatus:mod.status}),now)]);return{id:id?.id,status:mod.status,verified:Boolean(booking)}}
export async function deleteReview(identity:VisitPngUser,id:number){const user=await owner(identity);const review=await env.DB.prepare("SELECT id FROM reviews WHERE id=? AND user_id=?").bind(id,user.id).first();if(!review)throw new Error("Review not found");await env.DB.prepare("DELETE FROM reviews WHERE id=? AND user_id=?").bind(id,user.id).run()}



