import { integer, real, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const countries = sqliteTable("countries", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  code: text("code").notNull().unique(),
  name: text("name").notNull(),
  currencyCode: text("currency_code").notNull().default("PGK"),
  currencySymbol: text("currency_symbol").notNull().default("K"),
  defaultLocale: text("default_locale").notNull().default("en"),
  phoneCode: text("phone_code").notNull().default("+675"),
  isActive: integer("is_active", { mode: "boolean" }).notNull().default(true),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull()
});

export const countrySettings = sqliteTable("country_settings", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  countryId: integer("country_id").notNull().unique().references(() => countries.id),
  domain: text("domain"),
  heroTitle: text("hero_title").notNull(),
  heroSubtitle: text("hero_subtitle").notNull(),
  heroEyebrow: text("hero_eyebrow").notNull(),
  brandColor: text("brand_color").notNull().default("#1B6960"),
  accentColor: text("accent_color").notNull().default("#E77522"),
  logoUrl: text("logo_url"),
  faviconUrl: text("favicon_url"),
  mapCenterLat: real("map_center_lat").notNull().default(-6.314993),
  mapCenterLng: real("map_center_lng").notNull().default(143.95555),
  mapDefaultZoom: integer("map_default_zoom").notNull().default(6),
  taxRate: real("tax_rate").notNull().default(0.10),
  commissionRate: real("commission_rate").notNull().default(0.05),
  emergencyNumbers: text("emergency_numbers").notNull(),
  supportEmail: text("support_email").notNull(),
  supportPhone: text("support_phone").notNull(),
  featureFlags: text("feature_flags").notNull(),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull()
});

export const provinces=sqliteTable("provinces",{id:integer("id").primaryKey({autoIncrement:true}),countryId:integer("country_id").references(()=>countries.id),code:text("code").notNull().unique(),name:text("name").notNull(),region:text("region").notNull()});
export const destinations=sqliteTable("destinations",{id:integer("id").primaryKey({autoIncrement:true}),countryId:integer("country_id").references(()=>countries.id),provinceId:integer("province_id").notNull().references(()=>provinces.id),district:text("district"),slug:text("slug").notNull().unique(),name:text("name").notNull(),summary:text("summary").notNull(),latitude:real("latitude"),longitude:real("longitude"),coverImageUrl:text("cover_image_url"),sourceUrl:text("source_url"),isTestData:integer("is_test_data",{mode:"boolean"}).notNull().default(true)});
export const categories=sqliteTable("categories",{id:integer("id").primaryKey({autoIncrement:true}),countryId:integer("country_id").references(()=>countries.id),slug:text("slug").notNull().unique(),name:text("name").notNull(),icon:text("icon").notNull(),displayOrder:integer("display_order").notNull().default(0),isActive:integer("is_active",{mode:"boolean"}).notNull().default(true)});
export const providers=sqliteTable("providers",{id:integer("id").primaryKey({autoIncrement:true}),countryId:integer("country_id").references(()=>countries.id),slug:text("slug").notNull().unique(),tradingName:text("trading_name").notNull(),legalName:text("legal_name"),licenseNumber:text("license_number"),verificationStatus:text("verification_status").notNull().default("seeded_unverified"),sourceName:text("source_name"),sourceUrl:text("source_url"),isTestData:integer("is_test_data",{mode:"boolean"}).notNull().default(true)});
export const listings=sqliteTable("listings",{id:integer("id").primaryKey({autoIncrement:true}),countryId:integer("country_id").references(()=>countries.id),providerId:integer("provider_id").notNull().references(()=>providers.id),destinationId:integer("destination_id").notNull().references(()=>destinations.id),categoryId:integer("category_id").notNull().references(()=>categories.id),slug:text("slug").notNull().unique(),name:text("name").notNull(),summary:text("summary").notNull(),imageUrl:text("image_url").notNull(),photoCredit:text("photo_credit"),deepLinkUrl:text("deep_link_url"),tag:text("tag").notNull(),currency:text("currency").notNull().default("PGK"),basePrice:integer("base_price").notNull(),memberPrice:integer("member_price"),rating:real("rating").notNull().default(0),reviewCount:integer("review_count").notNull().default(0),publicationStatus:text("publication_status").notNull().default("published"),verificationStatus:text("verification_status").notNull().default("seeded_unverified"),isTestData:integer("is_test_data",{mode:"boolean"}).notNull().default(true),lastReviewedAt:text("last_reviewed_at")});
export const destinationPhotos=sqliteTable("destination_photos",{id:integer("id").primaryKey({autoIncrement:true}),destinationId:integer("destination_id").references(()=>destinations.id),listingId:integer("listing_id").references(()=>listings.id),imageUrl:text("image_url").notNull(),caption:text("caption"),credit:text("credit"),sourceUrl:text("source_url"),displayOrder:integer("display_order").notNull().default(0),createdAt:text("created_at").notNull()});

export const users=sqliteTable("users",{id:integer("id").primaryKey({autoIncrement:true}),countryId:integer("country_id").references(()=>countries.id),email:text("email").notNull().unique(),fullName:text("full_name"),preferredName:text("preferred_name"),mobile:text("mobile"),country:text("country").notNull().default("Papua New Guinea"),preferredLanguage:text("preferred_language").notNull().default("English"),role:text("role").notNull().default("traveller"),status:text("status").notNull().default("active"),createdAt:text("created_at").notNull(),updatedAt:text("updated_at").notNull()});
export const auditLogs=sqliteTable("audit_logs",{id:integer("id").primaryKey({autoIncrement:true}),countryId:integer("country_id").references(()=>countries.id),userId:integer("user_id").references(()=>users.id),actorEmail:text("actor_email").notNull(),action:text("action").notNull(),entityType:text("entity_type").notNull(),entityId:text("entity_id"),details:text("details"),createdAt:text("created_at").notNull()});
export const wishlists=sqliteTable("wishlists",{id:integer("id").primaryKey({autoIncrement:true}),userId:integer("user_id").notNull().references(()=>users.id),name:text("name").notNull(),privacy:text("privacy").notNull().default("private"),shareCode:text("share_code").unique(),createdAt:text("created_at").notNull(),updatedAt:text("updated_at").notNull()});
export const wishlistItems=sqliteTable("wishlist_items",{id:integer("id").primaryKey({autoIncrement:true}),wishlistId:integer("wishlist_id").notNull().references(()=>wishlists.id),listingId:integer("listing_id").notNull().references(()=>listings.id),note:text("note"),createdAt:text("created_at").notNull(),updatedAt:text("updated_at").notNull()});
export const trips=sqliteTable("trips",{id:integer("id").primaryKey({autoIncrement:true}),userId:integer("user_id").notNull().references(()=>users.id),name:text("name").notNull(),destination:text("destination").notNull(),startDate:text("start_date").notNull(),endDate:text("end_date").notNull(),travellerCount:integer("traveller_count").notNull().default(1),budget:integer("budget").notNull().default(0),interests:text("interests"),notes:text("notes"),shareCode:text("share_code").unique(),status:text("status").notNull().default("planning"),createdAt:text("created_at").notNull(),updatedAt:text("updated_at").notNull()});
export const tripCollaborators=sqliteTable("trip_collaborators",{id:integer("id").primaryKey({autoIncrement:true}),tripId:integer("trip_id").notNull().references(()=>trips.id),email:text("email").notNull(),role:text("role").notNull().default("view"),status:text("status").notNull().default("invited"),createdAt:text("created_at").notNull()});
export const itineraryItems=sqliteTable("itinerary_items",{id:integer("id").primaryKey({autoIncrement:true}),tripId:integer("trip_id").notNull().references(()=>trips.id),listingId:integer("listing_id").references(()=>listings.id),title:text("title").notNull(),itemType:text("item_type").notNull().default("activity"),scheduledDate:text("scheduled_date").notNull(),startTime:text("start_time"),endTime:text("end_time"),cost:integer("cost").notNull().default(0),bookingReference:text("booking_reference"),notes:text("notes"),position:integer("position").notNull().default(0),createdAt:text("created_at").notNull(),updatedAt:text("updated_at").notNull()});
export const membershipPlans=sqliteTable("membership_plans",{id:integer("id").primaryKey({autoIncrement:true}),countryId:integer("country_id").references(()=>countries.id),code:text("code").notNull().unique(),name:text("name").notNull(),audience:text("audience").notNull(),billingPeriod:text("billing_period").notNull(),price:integer("price").notNull(),currency:text("currency").notNull().default("PGK"),description:text("description").notNull(),isComplimentary:integer("is_complimentary",{mode:"boolean"}).notNull().default(false),isActive:integer("is_active",{mode:"boolean"}).notNull().default(true),isTestData:integer("is_test_data",{mode:"boolean"}).notNull().default(true)});
export const membershipBenefits=sqliteTable("membership_benefits",{id:integer("id").primaryKey({autoIncrement:true}),code:text("code").notNull().unique(),name:text("name").notNull(),description:text("description").notNull(),usageLimit:integer("usage_limit"),validationType:text("validation_type").notNull().default("member_number"),isActive:integer("is_active",{mode:"boolean"}).notNull().default(true)});
export const planBenefits=sqliteTable("plan_benefits",{planId:integer("plan_id").notNull().references(()=>membershipPlans.id),benefitId:integer("benefit_id").notNull().references(()=>membershipBenefits.id)});
export const membershipSubscriptions=sqliteTable("membership_subscriptions",{id:integer("id").primaryKey({autoIncrement:true}),userId:integer("user_id").notNull().references(()=>users.id),planId:integer("plan_id").notNull().references(()=>membershipPlans.id),memberNumber:text("member_number").notNull().unique(),status:text("status").notNull(),startDate:text("start_date").notNull(),expiryDate:text("expiry_date"),autoRenew:integer("auto_renew",{mode:"boolean"}).notNull().default(false),cancelAtPeriodEnd:integer("cancel_at_period_end",{mode:"boolean"}).notNull().default(false),createdAt:text("created_at").notNull(),updatedAt:text("updated_at").notNull()});
export const benefitRedemptions=sqliteTable("benefit_redemptions",{id:integer("id").primaryKey({autoIncrement:true}),subscriptionId:integer("subscription_id").notNull().references(()=>membershipSubscriptions.id),benefitId:integer("benefit_id").notNull().references(()=>membershipBenefits.id),token:text("token").notNull().unique(),status:text("status").notNull().default("issued"),redeemedAt:text("redeemed_at"),createdAt:text("created_at").notNull()});
export const loyaltyLedger=sqliteTable("loyalty_ledger",{id:integer("id").primaryKey({autoIncrement:true}),userId:integer("user_id").notNull().references(()=>users.id),points:integer("points").notNull(),reason:text("reason").notNull(),referenceType:text("reference_type"),referenceId:text("reference_id"),createdAt:text("created_at").notNull()});
export const listingInventory=sqliteTable("listing_inventory",{id:integer("id").primaryKey({autoIncrement:true}),listingId:integer("listing_id").notNull().references(()=>listings.id),inventoryDate:text("inventory_date").notNull(),availableQuantity:integer("available_quantity").notNull().default(0),heldQuantity:integer("held_quantity").notNull().default(0),unitPrice:integer("unit_price").notNull(),isTestData:integer("is_test_data",{mode:"boolean"}).notNull().default(true),updatedAt:text("updated_at").notNull()});
export const bookings=sqliteTable("bookings",{id:integer("id").primaryKey({autoIncrement:true}),userId:integer("user_id").notNull().references(()=>users.id),reference:text("reference").notNull().unique(),status:text("status").notNull().default("held"),currency:text("currency").notNull().default("PGK"),subtotal:integer("subtotal").notNull(),total:integer("total").notNull(),startDate:text("start_date").notNull(),endDate:text("end_date").notNull(),guestCount:integer("guest_count").notNull(),contactName:text("contact_name").notNull(),contactMobile:text("contact_mobile"),holdExpiresAt:text("hold_expires_at"),isTestData:integer("is_test_data",{mode:"boolean"}).notNull().default(true),createdAt:text("created_at").notNull(),updatedAt:text("updated_at").notNull()});
export const bookingItems=sqliteTable("booking_items",{id:integer("id").primaryKey({autoIncrement:true}),bookingId:integer("booking_id").notNull().references(()=>bookings.id),listingId:integer("listing_id").notNull().references(()=>listings.id),listingName:text("listing_name").notNull(),quantity:integer("quantity").notNull(),unitPrice:integer("unit_price").notNull(),lineTotal:integer("line_total").notNull(),createdAt:text("created_at").notNull()});
export const payments=sqliteTable("payments",{id:integer("id").primaryKey({autoIncrement:true}),userId:integer("user_id").notNull().references(()=>users.id),entityType:text("entity_type").notNull(),entityId:integer("entity_id").notNull(),provider:text("provider").notNull(),providerReference:text("provider_reference").notNull().unique(),status:text("status").notNull(),currency:text("currency").notNull().default("PGK"),amount:integer("amount").notNull(),isTestData:integer("is_test_data",{mode:"boolean"}).notNull().default(true),createdAt:text("created_at").notNull(),updatedAt:text("updated_at").notNull()});
export const reviews=sqliteTable("reviews",{id:integer("id").primaryKey({autoIncrement:true}),userId:integer("user_id").notNull().references(()=>users.id),listingId:integer("listing_id").notNull().references(()=>listings.id),bookingId:integer("booking_id").references(()=>bookings.id),verificationType:text("verification_type").notNull().default("unverified"),overallRating:integer("overall_rating").notNull(),valueRating:integer("value_rating"),serviceRating:integer("service_rating"),safetyRating:integer("safety_rating"),accessibilityRating:integer("accessibility_rating"),title:text("title").notNull(),body:text("body").notNull(),travelType:text("travel_type"),dateOfExperience:text("date_of_experience"),moderationStatus:text("moderation_status").notNull().default("published"),moderationReason:text("moderation_reason"),providerResponse:text("provider_response"),providerRespondedAt:text("provider_responded_at"),createdAt:text("created_at").notNull(),updatedAt:text("updated_at").notNull()});
export const reviewModerationEvents=sqliteTable("review_moderation_events",{id:integer("id").primaryKey({autoIncrement:true}),reviewId:integer("review_id").notNull().references(()=>reviews.id),actorUserId:integer("actor_user_id").references(()=>users.id),action:text("action").notNull(),reason:text("reason"),createdAt:text("created_at").notNull()});
export const reviewDisputes=sqliteTable("review_disputes",{id:integer("id").primaryKey({autoIncrement:true}),reviewId:integer("review_id").notNull().references(()=>reviews.id),raisedByUserId:integer("raised_by_user_id").notNull().references(()=>users.id),reason:text("reason").notNull(),status:text("status").notNull().default("open"),resolution:text("resolution"),createdAt:text("created_at").notNull(),updatedAt:text("updated_at").notNull()});
