import {env} from "./runtime";
import type {VisitPngUser} from "../app/auth";
import {getOrCreateAccount} from "./accounts";
import {ensureCatalogue} from "./catalogue";
const schema=[`CREATE TABLE IF NOT EXISTS wishlists (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,name TEXT NOT NULL,privacy TEXT NOT NULL DEFAULT 'private',share_code TEXT UNIQUE,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`,`CREATE INDEX IF NOT EXISTS wishlists_user_idx ON wishlists(user_id)`,`CREATE TABLE IF NOT EXISTS wishlist_items (id INTEGER PRIMARY KEY AUTOINCREMENT,wishlist_id INTEGER NOT NULL REFERENCES wishlists(id) ON DELETE CASCADE,listing_id INTEGER NOT NULL REFERENCES listings(id) ON DELETE CASCADE,note TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(wishlist_id,listing_id))`,`CREATE INDEX IF NOT EXISTS wishlist_items_list_idx ON wishlist_items(wishlist_id)`];
export type Wishlist={id:number;name:string;privacy:string;shareCode:string|null;items:WishlistItem[]};export type WishlistItem={id:number;listingId:number;note:string|null;createdAt:string;slug:string;name:string;summary:string;imageUrl:string;tag:string;currency:string;basePrice:number;memberPrice:number|null;rating:number;destination:string;province:string;categoryName:string;providerName:string};
export async function ensureWishlists(){await ensureCatalogue();await env.DB.batch(schema.map(sql=>env.DB.prepare(sql)))}
async function owner(identity:VisitPngUser){await ensureWishlists();return getOrCreateAccount(identity)}async function audit(userId:number,email:string,action:string,entityId:string,details:unknown){await env.DB.prepare(`INSERT INTO audit_logs (user_id,actor_email,action,entity_type,entity_id,details,created_at) VALUES (?,?,?,?,?,?,?)`).bind(userId,email,action,"wishlist",entityId,JSON.stringify(details),new Date().toISOString()).run()}async function assertList(userId:number,id:number){const row=await env.DB.prepare("SELECT id FROM wishlists WHERE id=? AND user_id=?").bind(id,userId).first();if(!row)throw new Error("Wishlist not found")}
export async function getWishlists(identity:VisitPngUser):Promise<Wishlist[]>{const user=await owner(identity);let lists=await env.DB.prepare("SELECT id,name,privacy,share_code AS shareCode FROM wishlists WHERE user_id=? ORDER BY updated_at DESC").bind(user.id).all<Omit<Wishlist,"items">>();if(!lists.results.length){await createWishlist(identity,"My Wishlist");lists=await env.DB.prepare("SELECT id,name,privacy,share_code AS shareCode FROM wishlists WHERE user_id=? ORDER BY updated_at DESC").bind(user.id).all()}const out:Wishlist[]=[];for(const list of lists.results as Omit<Wishlist,"items">[]){const items=await env.DB.prepare(`SELECT wi.id,wi.listing_id AS listingId,wi.note,wi.created_at AS createdAt,l.slug,l.name,l.summary,l.image_url AS imageUrl,l.tag,l.currency,l.base_price AS basePrice,l.member_price AS memberPrice,l.rating,d.name AS destination,pv.name AS province,c.name AS categoryName,p.trading_name AS providerName FROM wishlist_items wi JOIN listings l ON l.id=wi.listing_id JOIN destinations d ON d.id=l.destination_id JOIN provinces pv ON pv.id=d.province_id JOIN categories c ON c.id=l.category_id JOIN providers p ON p.id=l.provider_id WHERE wi.wishlist_id=? ORDER BY wi.created_at DESC`).bind(list.id).all<WishlistItem>();out.push({...list,items:items.results})}return out}
export async function getSharedWishlist(code:string){await ensureWishlists();const list=await env.DB.prepare("SELECT id,name,privacy,share_code AS shareCode FROM wishlists WHERE share_code=? AND privacy IN ('link','public')").bind(code).first<Omit<Wishlist,"items">>();if(!list)return null;const items=await env.DB.prepare(`SELECT wi.id,wi.listing_id AS listingId,wi.note,wi.created_at AS createdAt,l.slug,l.name,l.summary,l.image_url AS imageUrl,l.tag,l.currency,l.base_price AS basePrice,l.member_price AS memberPrice,l.rating,d.name AS destination,pv.name AS province,c.name AS categoryName,p.trading_name AS providerName FROM wishlist_items wi JOIN listings l ON l.id=wi.listing_id JOIN destinations d ON d.id=l.destination_id JOIN provinces pv ON pv.id=d.province_id JOIN categories c ON c.id=l.category_id JOIN providers p ON p.id=l.provider_id WHERE wi.wishlist_id=? ORDER BY wi.created_at DESC`).bind(list.id).all<WishlistItem>();return{...list,items:items.results}}
export async function createWishlist(identity:VisitPngUser,name:string){const user=await owner(identity);const now=new Date().toISOString();await env.DB.prepare("INSERT INTO wishlists (user_id,name,privacy,created_at,updated_at) VALUES (?,?,'private',?,?)").bind(user.id,name.slice(0,60),now,now).run();await audit(user.id,identity.email,"wishlist_created",name.slice(0,60),{name})}
export async function updateWishlist(identity:VisitPngUser,id:number,input:{name?:string;privacy?:string}){const user=await owner(identity);await assertList(user.id,id);const privacy=["private","link","public"].includes(input.privacy||"")?input.privacy:undefined;if(privacy){const shareCode=privacy==="link"?crypto.randomUUID().replaceAll("-","").slice(0,16):null;await env.DB.prepare("UPDATE wishlists SET name=COALESCE(?,name),privacy=?,share_code=?,updated_at=? WHERE id=? AND user_id=?").bind(input.name?.slice(0,60)||null,privacy,shareCode,new Date().toISOString(),id,user.id).run()}else await env.DB.prepare("UPDATE wishlists SET name=COALESCE(?,name),updated_at=? WHERE id=? AND user_id=?").bind(input.name?.slice(0,60)||null,new Date().toISOString(),id,user.id).run();await audit(user.id,identity.email,"wishlist_updated",String(id),input)}
export async function deleteWishlist(identity:VisitPngUser,id:number){const user=await owner(identity);await assertList(user.id,id);await env.DB.prepare("DELETE FROM wishlists WHERE id=? AND user_id=?").bind(id,user.id).run();await audit(user.id,identity.email,"wishlist_deleted",String(id),{})}
export async function addItem(identity:VisitPngUser,listId:number,listingId:number){const user=await owner(identity);await assertList(user.id,listId);const listing=await env.DB.prepare("SELECT id FROM listings WHERE id=? AND publication_status='published'").bind(listingId).first();if(!listing)throw new Error("Listing not found");const now=new Date().toISOString();await env.DB.prepare("INSERT INTO wishlist_items (wishlist_id,listing_id,created_at,updated_at) VALUES (?,?,?,?) ON CONFLICT(wishlist_id,listing_id) DO NOTHING").bind(listId,listingId,now,now).run();await env.DB.prepare("UPDATE wishlists SET updated_at=? WHERE id=?").bind(now,listId).run();await audit(user.id,identity.email,"wishlist_item_added",String(listId),{listingId})}
export async function updateItem(identity:VisitPngUser,itemId:number,input:{note?:string;wishlistId?:number}){const user=await owner(identity);const item=await env.DB.prepare("SELECT wi.id,wi.wishlist_id AS wishlistId FROM wishlist_items wi JOIN wishlists w ON w.id=wi.wishlist_id WHERE wi.id=? AND w.user_id=?").bind(itemId,user.id).first<{id:number;wishlistId:number}>();if(!item)throw new Error("Saved item not found");if(input.wishlistId)await assertList(user.id,input.wishlistId);await env.DB.prepare("UPDATE wishlist_items SET note=COALESCE(?,note),wishlist_id=COALESCE(?,wishlist_id),updated_at=? WHERE id=?").bind(input.note?.slice(0,280)??null,input.wishlistId||null,new Date().toISOString(),itemId).run();await audit(user.id,identity.email,"wishlist_item_updated",String(item.wishlistId),input)}
export async function removeItem(identity:VisitPngUser,itemId:number){const user=await owner(identity);const item=await env.DB.prepare("SELECT wi.id,wi.wishlist_id AS wishlistId FROM wishlist_items wi JOIN wishlists w ON w.id=wi.wishlist_id WHERE wi.id=? AND w.user_id=?").bind(itemId,user.id).first<{wishlistId:number}>();if(!item)throw new Error("Saved item not found");await env.DB.prepare("DELETE FROM wishlist_items WHERE id=?").bind(itemId).run();await audit(user.id,identity.email,"wishlist_item_removed",String(item.wishlistId),{itemId})}

